# Generated by Django 4.2.7 on 2023-12-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_alter_user_google_id_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='google_id_int1',
        ),
        migrations.AddField(
            model_name='user',
            name='google_id_int2',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
