# Generated by Django 4.2.4 on 2023-10-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_date_post_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
