# Generated by Django 4.2.4 on 2023-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('tu', 'Tutorial'), ('hg', 'How-To Guides'), ('nw', 'News and Updates'), ('pr', 'Product Reviews'), ('op', 'Opinion Pieces'), ('tp', 'Top x'), ('ps', 'Personal Stories and Experiences'), ('cs', 'Case Studies'), ('in', 'Interviews'), ('ig', 'Infographics'), ('gp', 'Guest Posts'), ('rp', 'Roundup Posts'), ('rc', 'Reviews and Comparisons'), ('rt', 'Resources and Tools'), ('td', 'Travel Destinations'), ('re', 'Recipes'), ('fa', 'Fashion'), ('ft', 'Fitness Tips'), ('nu', 'Nutrition'), ('mh', 'Mental Health'), ('dp', 'DIY Projects'), ('im', 'Inspirational or Motivational'), ('he', 'History and Education'), ('qa', 'Q&A'), ('aq', 'FAQ')], default='tu', max_length=2),
            preserve_default=False,
        ),
    ]
