# Generated by Django 4.2.4 on 2023-11-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_post_thumbnail_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
