# Generated by Django 4.2.7 on 2023-12-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_rename_comments_comment_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('sexual', 'Sexual Content'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=20),
        ),
    ]
